schemadotorg_options.settings:
  type: config_object
  label: 'Schema.org Options settings'
  mapping:
    schema_property_allowed_values:
      type: sequence
      label: 'Schema.org property'
      sequence:
        type: sequence
        label: 'Allowed values'
        sequence:
          type: text
          label: Text
    schema_property_allowed_values_suffixes:
      type: sequence
      label: 'Schema.org property allowed values suffixes'
      sequence:
        type: text
        label: 'Schema.org property allowed values suffix'
    allowed_value_uris:
      type: sequence
      label: 'Allowed value URIs'
      sequence:
        type: uri
        label: 'Allowed values URI'
