<?php
use Drupal\node\Entity\Node;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\HtmlCommand;
use Drupal\Core\Ajax\InvokeCommand;
use Drupal\Core\Ajax\ReplaceCommand;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\user\Entity\User;
use Drupal\Core\Url;
use Drupal\block\Entity\Block;
use Drupal\taxonomy\Entity\Term;
/**
 * @File
 * Example custom module for Drupal 8.
 */

/**
 * Implementing hook_theme().
 */

function userprofile_theme() {
	return array(
   		'profile_template' => array(
            'variables' => array('arr_data' => NULL),
            'template' => 'profile-custom-template',
        ),
  	);
}

?>