<?php
use Drupal\node\Entity\Node;
use Drupal\Core\Ajax\AjaxResponse;
use Drupal\Core\Ajax\HtmlCommand;
use Drupal\Core\Ajax\InvokeCommand;
use Drupal\Core\Ajax\ReplaceCommand;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\user\Entity\User;
use Drupal\Core\Url;
use Drupal\block\Entity\Block;
use Drupal\taxonomy\Entity\Term;
/**
 * @File
 * Example custom module for Drupal 8.
 */

/**
 * Implementing hook_theme().
 */
function userprofile_page_attachments(array &$attachments) {
    $current_path = \Drupal::service("path.current")->getPath();
    if($current_path == '/doctor-dashboard'){
        $attachments['#attached']['library'][] = 'userprofile/custom-styles';
    }
	$attachments['#attached']['library'][] = 'userprofile/userprofile';
}


function userprofile_theme() {
	return array(
   		'profile_template' => array(
            'variables' => array('arr_data' => NULL),
            'template' => 'user-profile',
        ),
        'profile_doctor_template' => array(
            'variables' => array('arr_data' => NULL),
            'template' => 'doctor-profile',
        ),
        'profile_blog_template' => array(
            'variables' => array('arr_data' => NULL),
            'template' => 'blog',
        ),
        'profile_all_blog_template' => array(
            'variables' => array('blog_data' => NULL),
            'template' => 'all-blog',
        ),
        'book_appointment_template' => array(
            'variables' => array('arr_data' => NULL),
            'template' => 'book-appointment-custom-template',
        ),
        'dashboard_template' => array(
            'variables' => array('arr_data' => NULL),
            'template' => 'dashboard-custom-template',
        ),

  	);
}

?>