<?php

/**
 * @file
 * Set allowed values for list (options) fields.
 */

declare(strict_types=1);

use Drupal\Core\Field\FieldItemInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Language\LanguageManager;
use Drupal\Core\Locale\CountryManager;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\Core\TypedData\OptionsProviderInterface;

/**
 * Implements hook_schemadotorg_property_field_type_alter().
 */
function schemadotorg_options_schemadotorg_property_field_type_alter(array &$field_types, string $schema_type, string $schema_property): void {
  /** @var \Drupal\schemadotorg\SchemaDotOrgSchemaTypeManagerInterface $schema_type_manager */
  $schema_type_manager = \Drupal::service('schemadotorg.schema_type_manager');

  // Set default field type for Schema.org types/properties with allowed values.
  $schema_property_allowed_values = \Drupal::config('schemadotorg_options.settings')
    ->get('schema_property_allowed_values');
  $setting_parts = [
    'schema_type' => $schema_type,
    'schema_property' => $schema_property,
  ];
  if ($schema_type_manager->getSetting($schema_property_allowed_values, $setting_parts)) {
    $field_types = ['list_string' => 'list_string'] + $field_types;
    return;
  }

  // Do not adjust the property's field type if a default field type is defined.
  /** @var \Drupal\schemadotorg\SchemaDotOrgEntityFieldManagerInterface $schema_field_manager */
  $schema_field_manager = \Drupal::service('schemadotorg.entity_field_manager');
  $default_field = $schema_field_manager->getPropertyDefaultField($schema_type, $schema_property);
  if (!empty($default_field['type'])) {
    return;
  }

  /** @var \Drupal\schemadotorg\SchemaDotOrgSchemaTypeManagerInterface $schema_type_manager */
  $schema_type_manager = \Drupal::service('schemadotorg.schema_type_manager');
  $range_includes = $schema_type_manager->getPropertyRangeIncludes($schema_property);
  foreach ($range_includes as $range_include) {
    // Set default field type to list string for allowed values function.
    $allowed_values_function = 'schemadotorg_options_allowed_values_' . strtolower($range_include);
    if (function_exists($allowed_values_function)) {
      $field_types = ['list_string' => 'list_string'] + $field_types;
      return;
    }

    // Set default field type to list string for enumerations.
    if ($schema_type_manager->isEnumerationType($range_include)) {
      $field_types = ['list_string' => 'list_string'] + $field_types;
      return;
    }
  }
}

/**
 * Implements hook_schemadotorg_property_field_alter().
 */
function schemadotorg_options_schemadotorg_property_field_alter(
  string $schema_type,
  string $schema_property,
  array &$field_storage_values,
  array &$field_values,
  ?string &$widget_id,
  array &$widget_settings,
  ?string &$formatter_id,
  array &$formatter_settings,
): void {
  // Only alter 'list_string' fields without allowed values.
  if ($field_storage_values['type'] !== 'list_string'
    || !empty($field_storage_values['settings']['allowed_values'])
    || !empty($field_storage_values['settings']['allowed_values_function'])) {
    return;
  }

  // Set allowed values based on the Schema.org property.
  /** @var \Drupal\schemadotorg\SchemaDotOrgSchemaTypeManagerInterface $schema_type_manager */
  $schema_type_manager = \Drupal::service('schemadotorg.schema_type_manager');
  $schema_property_allowed_values_settings = \Drupal::config('schemadotorg_options.settings')
    ->get('schema_property_allowed_values');
  $setting_parts = [
    'schema_type' => $schema_type,
    'schema_property' => $schema_property,
  ];
  $schema_property_allowed_values = $schema_type_manager->getSetting($schema_property_allowed_values_settings, $setting_parts);
  if ($schema_property_allowed_values) {
    $field_storage_values['settings'] = [
      'allowed_values' => $schema_property_allowed_values,
      'allowed_values_function' => '',
    ];
    return;
  }

  /** @var \Drupal\schemadotorg\SchemaDotOrgSchemaTypeManagerInterface $schema_type_manager */
  $schema_type_manager = \Drupal::service('schemadotorg.schema_type_manager');

  $property_definition = $schema_type_manager->getProperty($schema_property);
  if (!$property_definition) {
    return;
  }

  // Set allowed values based the Schema.org types range includes.
  $range_includes = $schema_type_manager->parseIds($property_definition['range_includes']);

  // Set allowed values function if it exists.
  // @see schemadotorg_options_allowed_values_country()
  // @see schemadotorg_options_allowed_values_language()
  foreach ($range_includes as $range_include) {
    $allowed_values_function = 'schemadotorg_options_allowed_values_' . strtolower($range_include);
    if (function_exists($allowed_values_function)) {
      $field_storage_values['settings'] = [
        'allowed_values' => [],
        'allowed_values_function' => $allowed_values_function,
      ];
      return;
    }
  }

  // Set allowed values from all range includes that are enumerations.
  $allowed_values = [];
  foreach ($range_includes as $range_include) {
    if ($schema_type_manager->isEnumerationType($range_include)) {
      $allowed_values += $schema_type_manager->getTypeChildrenAsOptions($range_include);
    }
  }

  // Remove allowed values suffixes based on the Schema.org property.
  $schema_property_allowed_values_suffix = \Drupal::config('schemadotorg_options.settings')
    ->get("schema_property_allowed_values_suffixes.$schema_property");
  if ($schema_property_allowed_values_suffix) {
    foreach ($allowed_values as $value => $text) {
      $allowed_values[$value] = str_replace(' ' . $schema_property_allowed_values_suffix, '', $text);
    }
  }

  if (!empty($allowed_values)) {
    $field_storage_values['settings'] = [
      'allowed_values' => $allowed_values,
      'allowed_values_function' => '',
    ];
  }
}

/* ************************************************************************** */
// Schema.org JSON-LD.
/* ************************************************************************** */

/**
 * Implements hook_schemadotorg_jsonld_schema_property_alter().
 */
function schemadotorg_options_schemadotorg_jsonld_schema_property_alter(mixed &$value, FieldItemInterface $item, BubbleableMetadata $bubbleable_metadata): void {
  if ($item instanceof OptionsProviderInterface && is_string($value)) {
    $uri = \Drupal::config('schemadotorg_options.settings')
      ->get("allowed_value_uris.$value");
    if ($uri) {
      $value = $uri;
    }
  }
}

/* ************************************************************************** */
// Schema.org properties settings form.
/* ************************************************************************** */

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::afterBuildDetails
 * @see \Drupal\schemadotorg\Form\SchemaDotOrgSettingsFormBase::formAlter
 */
function schemadotorg_options_form_schemadotorg_properties_settings_form_alter(array &$form, FormStateInterface $form_state): void {
  $form['schemadotorg_options'] = [
    '#type' => 'details',
    '#title' => t('Options settings'),
  ];
  $form['schemadotorg_options']['schema_property_allowed_values'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Schema.org property allowed values'),
    '#description' => t('Enter Schema.org types and properties with allowed values.'),
    '#description_link' => 'properties',
    '#example' => '
propertyName:
  option01: Option 1
  option02: Options 2
SchemaType--propertyName:
  option01: Option 1
  option02: Options 2
',
  ];
  $form['schemadotorg_options']['schema_property_allowed_values_suffixes'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Schema.org property allowed values suffixes'),
    '#description' => t('Enter Schema.org properties with allowed values suffixes that should be removed..'),
    '#description_link' => 'properties',
    '#example' => 'propertyName: suffix',
  ];
  $form['schemadotorg_options']['allowed_value_uris'] = [
    '#type' => 'schemadotorg_settings',
    '#title' => t('Allowed value URIs'),
    '#description' => t('Enter URIs to be used in the Schema.org JSON-LD for an allowed value.')
      . ' ' . t('The allowed value URIs allows internal option machine names to mapped to  a well known URL from Wikipedia or Wikidata'),
    '#description_link' => 'properties',
    '#example' => "
warning: 'https://www.wikidata.org/wiki/Q1759104'
emergency: 'https://www.wikidata.org/wiki/Q5070802'
error: 'https://www.wikidata.org/wiki/Q29485'
information: 'https://www.wikidata.org/wiki/Q11028'
condition: 'https://www.wikidata.org/wiki/Q813912'
",
  ];
}

/* ************************************************************************** */
// Allowed values function callbacks.
/* ************************************************************************** */

/**
 * HOOK_options_allowed_values_SCHEMA_TYPE()
 */
function schemadotorg_options_allowed_values_country(): array {
  return CountryManager::getStandardList();
}

/**
 * HOOK_options_allowed_values_SCHEMA_TYPE()
 */
function schemadotorg_options_allowed_values_language(): array {
  $languages = LanguageManager::getStandardLanguageList();
  unset($languages['en-x-simple']);
  $allowed_values = [];
  foreach ($languages as $language) {
    $allowed_values[$language[0]] = $language[0];
  }
  return $allowed_values;
}
