schemadotorg_jsonapi.settings:
  type: config_object
  label: 'Schema.org JSON:API settings'
  mapping:
    default_base_fields:
      type: sequence
      label: 'Default base fields'
      sequence:
        type: string
        label: 'Default base field'
    custom_public_names:
      type: sequence
      label: 'Custom public names'
      sequence:
        type: string
        label: 'Custom public name'
    resource_type_schemadotorg:
      type: boolean
      label: 'Use Schema.org type as the resource type and path name'
    resource_base_field_schemadotorg:
      type: boolean
      label: 'Use Schema.org property as the resource base field name/alias'
    resource_field_schemadotorg:
      type: boolean
      label: 'Use Schema.org property as the resource field name/alias'
