schemadotorg.settings:
  type: config_object
  label: 'Schema.org settings'
  mapping:
    requirements:
      type: mapping
      label: Requirements
      mapping:
        recommended_modules:
          type: boolean
          label: 'Check for recommended modules'
    schema_data:
      type: mapping
      label: 'Schema.org data'
      mapping:
        file:
          type: string
          label: 'Schema.org data file or URL'
    schema_types:
      type: mapping
      label: 'Schema.org types'
      mapping:
        default_types:
          type: sequence
          label: 'Default types'
          sequence:
            type: mapping
            label: 'Default types'
            mapping:
              name:
                type: string
                label: 'Machine name'
              label:
                type: text
                label: Label
              description:
                type: text
                label: Description
        main_properties:
          type: sequence
          label: 'Schema.org types main properties'
          sequence:
            type: string
            label: 'Schema.org type main property'
        default_properties:
          type: sequence
          label: 'Default Schema.org type properties'
          sequence:
            type: sequence
            label: 'Schema.org type'
            sequence:
              type: string
              label: 'Schema.org property'
        default_property_values:
          type: sequence
          label: 'Default Schema.org type property values'
          sequence:
            type: sequence
            label: 'Schema.org type'
            sequence:
              type: string
              label: 'Schema.org property value'
        default_field_types:
          type: sequence
          label: 'Default field types'
          sequence:
            type: sequence
            label: 'Schema.org type'
            sequence:
              type: string
              label: 'Field types'
    schema_properties:
      type: mapping
      label: 'Schema.org properties'
      mapping:
        range_includes:
          type: sequence
          label: 'Schema.org type/property custom range includes'
          sequence:
            type: sequence
            label: 'Schema.org types/properties'
            sequence:
              type: string
              label: 'Schema.org type'
        ignored_properties:
          type: sequence
          label: 'Ignored properties'
          sequence:
            type: string
            label: 'Schema.org property'
        default_fields:
          type: sequence
          label: 'Default fields'
          sequence:
            type: mapping
            label: 'Default field'
            mapping:
              type:
                type: string
                label: Type
              name:
                type: string
                label: Name
              label:
                type: text
                label: Label
              description:
                type: text
                label: Description
              unlimited:
                type: boolean
                label: 'Unlimited values'
              required:
                type: boolean
                label: 'Required field'
              max_length:
                type: integer
                label: 'Maximum length'
              default_value:
                type: ignore
                label: 'Default value'
        default_field_formatter_settings:
          type: sequence
          label: 'Default field formatter settings'
          sequence:
            type: mapping
            label: 'Default field formatter setting'
            mapping:
              label:
                type: string
                label: Label
        default_field_types:
          type: sequence
          label: 'Default field types'
          sequence:
            type: sequence
            label: 'Schema.org property'
            sequence:
              type: string
              label: 'Field types'
        default_field_weights:
          type: sequence
          label: 'Default field weights'
          sequence:
            type: string
            label: 'Default field weight'
