schemadotorg_node.settings:
  type: config_object
  label: 'Schema.org Node settings'
  mapping:
    menu_ui:
      type: sequence
      label: 'Schema.org types menu UI'
      sequence:
        type: mapping
        label: 'Schema.org type menu UI'
        mapping:
          available_menus:
            type: sequence
            label: 'Available menus'
            sequence:
              type: string
              label: 'Menu machine name'
          parent:
            type: string
            label: 'Parent'
    display_submitted:
      type: sequence
      label: 'Schema.org types display submitted'
      sequence:
        type: boolean
        label: 'Schema.org type display submitted'
