schemadotorg_jsonld.settings:
  type: config_object
  label: 'Schema.org JSON-LD settings'
  mapping:
    schema_property_order:
      type: sequence
      label: 'Schema.org property order'
      sequence:
        type: string
        label: 'Schema.org property'
    schema_property_image_styles:
      type: sequence
      label: 'Field name image styles'
      sequence:
        type: string
        label: 'Field name image style'
    schema_type_entity_references_display:
      type: sequence
      label: 'Schema.org type entity references by'
      sequence:
        type: string
        label: 'Schema.org type entity reference by'
    entity_types_exclude_url:
      type: sequence
      label: 'Entity types exclude URL'
      sequence:
        type: string
        label: 'Entity type exclude URL'
