schemadotorg_field_group.settings:
  type: config_object
  label: 'Schema.org Field group settings'
  mapping:
    default_field_groups:
      type: sequence
      label: 'Default entity type field groups'
      sequence:
        type: sequence
        label: 'Default field groups'
        sequence:
          type: mapping
          label: 'Default field group'
          mapping:
            label:
              type: string
              label: Label
            properties:
              type: sequence
              label: Properties
              sequence:
                type: string
                label: Property
    default_schema_type_field_groups:
      type: sequence
      label: 'Default Schema.org type field groups'
      sequence:
        type: string
        label: 'Default Schema.org type field group'
    default_form_type:
      type: string
      label: 'Default field group form type'
    default_view_type:
      type: string
      label: 'Default field group view type'
    disable_field_groups:
      type: sequence
      label: 'Disable field groups'
      sequence:
        type: string
        label: 'Disable field group'
