schemadotorg_jsonld_preview.settings:
  type: config_object
  label: 'Schema.org JSON-LD Preview settings'
  mapping:
    node_task:
      type: boolean
      label: 'Display JSON-LD preview as a node tab/task.'
