<?php

/**
 * @file
 * Installation hooks for the Schema.org Blueprints Block Content module.
 */

declare(strict_types=1);

/**
 * Implements hook_install().
 */
function schemadotorg_block_content_install(bool $is_syncing): void {
  if ($is_syncing) {
    return;
  }

  /** @var \Drupal\schemadotorg\SchemaDotOrgMappingManagerInterface $mapping_manager */
  $mapping_manager = \Drupal::service('schemadotorg.mapping_manager');
  $mapping_manager->createDefaultTypes('block_content');
}
