schemadotorg_taxonomy.settings:
  type: config_object
  label: 'Schema.org Taxonomy settings'
  mapping:
    default_field_groups:
      type: sequence
      label: 'Default field groups'
      sequence:
        type: string
        label: 'Default field group'
    default_vocabularies:
      type: sequence
      label: 'Default vocabularies'
      sequence:
        type: mapping
        label: 'Default vocabulary'
        mapping:
          id:
            type: string
            label: 'Vocabulary ID'
          label:
            type: text
            label: 'Vocabulary name'
          description:
            type: text
            label: 'Vocabulary description'
          auto_create:
            type: boolean
            label: 'Auto create'
          group:
            type: string
            label: 'Group name'
    schema_property_vocabularies:
      type: sequence
      label: 'Default properties'
      sequence:
        type: mapping
        label: 'Default property'
        mapping:
          id:
            type: string
            label: 'Vocabulary ID'
          label:
            type: text
            label: 'Vocabulary name'
          description:
            type: text
            label: 'Vocabulary description'
